# Generated by Django 5.0.6 on 2024-06-09 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('networking', '0004_alter_customuser_options_alter_customuser_managers_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
    ]
